#! /usr/bin/env bash
#MISE description="activations"

eval "$("${HOME}"/.local/bin/mise activate bash --shims)"

DOTFILES_DIR="$(pwd)"
activation_cache_file="${DOTFILES_DIR}/custom/activation-cache.gen.zsh"
:> "$activation_cache_file"

function _evalcache() {
  echo "Evaluating: $*"
  which "$1" 
  "$@" >> "$activation_cache_file"
}


_evalcache starship init zsh
_evalcache /opt/homebrew/bin/brew shellenv
_evalcache try init ~/src/tries
_evalcache fzf --zsh
_evalcache zoxide init zsh --cmd cd
