#! /usr/bin/env zsh
#MISE description="activations"

echo "activations"

eval "$(${HOME}/.local/bin/mise activate zsh --shims)"

DOTFILES_DIR="$(pwd)"
activation_cache_file="${DOTFILES_DIR}/custom/activation-cache.gen.zsh"

function _evalcache() {
  "$@" >> "$activation_cache_file"
}


_evalcache starship init zsh
_evalcache /opt/homebrew/bin/brew shellenv
_evalcache try init ~/src/tries
_evalcache fzf --zsh
_evalcache zoxide init zsh --cmd cd
