#! /usr/bin/env bash
#MISE description="bundle"
#MISE depends=["init:activations", "init:plugins"]

# Custom Config Locations
DOTFILES_DIR="$(pwd)"

# ====== Bundle custom/*.zsh scripts =========
# Configure Bundle Path
bundle_file="${DOTFILES_DIR}/custom.bundle.zsh"
custom_dir="${DOTFILES_DIR}/custom"

# Generate bundled file when it doesn't exist

: >"${bundle_file}"

for f in "${custom_dir}"/*.gen.zsh; do
	echo "  Appending $f..."
	{
		echo "# --- Source: ${f:t} ---" 
		cat "$f"
		echo -e 
	} >> "${bundle_file}"
done

# Concatinate scripts sequencially
for f in "${custom_dir}"/[0-9][0-9]-*.zsh; do
	echo "  Appending $f..."
	{
		echo "# --- Source: ${f:t} ---"
		cat "$f"
		echo -e
	} >> "${bundle_file}"
done

echo "✅ Bundle created: ${bundle_file}"