[tasks.format]
description = "Format TOML & ZSH files"
run = "taplo format; shfmt -l -w zshrc ./custom/*.zsh"

[tasks.clean]
description = "Clean cache files"
run = [
    "rm -rf */**.zwc",
    "rm -rf custom.bundle.zsh*",
    "rm -rf ~/.zsh-evalcache",
    "rm -rf ~/.cache/zsh_*",
    "rm -f ~/.zshrc.zwc",
    "rm -f ~/.zshrc",
    "rm -f ./custom/*.gen.zsh",
]

[tasks.reinstall]
description = "Reinstall plugins and regenerate cache files"
depends = "clean"
run = [
    'if [ ! -d "$HOME/.config/mise" ]; then mkdir -p ~/.config/mise; fi',
    'cp ./config/mise.global.toml ~/.config/mise/config.toml',
    'if [ ! -d "$HOME/.config/ghostty" ]; then mkdir -p ~/.config/ghostty; fi',
    'cp ./config/ghostty/config ~/.config/ghostty/config',
    'cp ./config/vim/.vimrc ~/.vimrc',
    'mise install',
    "cp zshrc ~/.zshrc",
    "zsh ./init/load-plugins.zsh",
    "zsh ./init/init-activation-scripts.zsh",
]

[tasks.install]
description = "Install tools and dependencies"
run = [
]


[tools]
fzf = "latest"
"aqua:starship" = "latest"
bat = "latest"

# Dev tools
shellcheck = "latest"
shfmt = "latest"
taplo = "latest"
