[tasks.format]
description = "Format TOML & ZSH files"
run = "taplo format; shfmt -l -w zshrc ./custom/*.zsh"

[tasks.clean]
description = "Clean cache files"
run = "rm -rf ~/.cache/zsh_* */**.zwc ./*.zwc ~/.zsh-evalcache ./custom.bundle.zsh"

[tasks.reinstall]
description = "Clean and reinstall all dependencies"
depends = "clean"
run = "sheldon lock --reinstall"

[tools]
"github:8gaU8/try-go" = { version = "latest", asset_pattern = "try" }
fzf = "latest"
"aqua:starship" = "latest"
"github:rossmacarthur/sheldon" = "latest"
eza = "latest"
bat = "latest"

# Dev tools
shellcheck = "latest"
shfmt = "latest"
taplo = "latest"
