[tasks.format]
description = "Format TOML & ZSH files"
run = "taplo format; shfmt -l -w zshrc ./custom/*.zsh"

[tasks.clean]
description = "Clean cache files"
run = [
    "rm -rf */**.zwc",
    "rm -rf custom.bundle.zsh",
    "rm -rf ~/.zsh-evalcache",
    "rm -rf ~/.cache/zsh_*",
    "rm -f ~/.zshrc.zwc",
    "rm -f ~/.zshrc",
    "rm -f ./custom/*.gen.zsh",
]

[tasks.reinstall]
description = "Reinstall plugins and regenerate cache files"
depends = "clean"
run = [
    "cp zshrc ~/.zshrc",
    "zsh ./init/load-plugins.zsh",
    "zsh ./init/init-activation-scripts.zsh",
]

[tools]
fzf = "latest"
"aqua:starship" = "latest"
bat = "latest"

# Dev tools
shellcheck = "latest"
shfmt = "latest"
taplo = "latest"
