[tools]
gemini-cli = "latest"
node = "24"
pnpm = "latest"

[tasks."apply-karabiner-config"]
description = "Apply the Karabiner configuration"
alias = ["k"]
run = ["pnpm tsx src/index.ts"]

[tasks.fix]
description = "Run code formatters and linters"
alias = ["f"]
run = ["pnpm exec biome check --write"]

