#! /usr/bin/env zsh
#MISE description="Make symlinks for dotfiles"
echo "Linking dotfiles..."

DOTFILES="${HOME}/dotfiles"

# Link vimrc
ln -sf "${DOTFILES}/config/vim/.vimrc" "${HOME}/.vimrc"

# link mise config
# Create config directory if it doesn't exist
mkdir -p "${HOME}/.config/mise"
ln -sf "${DOTFILES}/config/mise/config.toml" "${HOME}/.config/mise/config.toml"

# link ghostty config
# Create config directory if it doesn't exist
mkdir -p "${HOME}/.config/ghostty"
ln -sf "${DOTFILES}/config/ghostty/config" "${HOME}/.config/ghostty/config"

ln -sf "${DOTFILES}/config/starship.toml" "${HOME}/.config/starship.toml"

ln -sf "${DOTFILES}/zsh/zshrc" "${HOME}/.zshrc"

ln -sf "${DOTFILES}/config/sheldon/plugins.toml" "${HOME}/.config/sheldon/plugins.toml"
