#! /usr/bin/env zsh
#MISE description="Make symlinks for dotfiles"
echo "Linking dotfiles..."

DOTFILES="${HOME}/dotfiles"

ln -sf "${DOTFILES}/zsh/zshrc" "${HOME}/.zshrc"

mkdir -p "${HOME}/.config/mise"
ln -sf "${DOTFILES}/config/mise/config.toml" "${HOME}/.config/mise/config.toml"

mkdir -p "${HOME}/.config/sheldon"
ln -sf "${DOTFILES}/zsh/sheldon/plugins.toml" "${HOME}/.config/sheldon/plugins.toml"

mkdir -p "${HOME}/.config/ghostty"
ln -sf "${DOTFILES}/config/ghostty/config" "${HOME}/.config/ghostty/config"

ln -sf "${DOTFILES}/config/starship.toml" "${HOME}/.config/starship.toml"
ln -sf "${DOTFILES}/config/vim/.vimrc" "${HOME}/.vimrc"
