#! /usr/bin/env bash
#MISE description="Reinstall dotfiles"
#MISE depends=["clean", "init"]
echo "Reinstalling dotfiles..."

# Link vimrc
ln -sf "${DOTFILES}/config/vim/.vimrc" "${HOME}/.vimrc"

# link mise config
# Create config directory if it doesn't exist
mkdir -p "${HOME}/.config/mise"
ln -sf "${DOTFILES}/config/mise.global.toml" "${HOME}/.config/mise/config.toml"

# link ghostty config
# Create config directory if it doesn't exist
mkdir -p "${HOME}/.config/ghostty"
ln -sf "${DOTFILES}/config/ghostty/config.toml" "${HOME}/.config/ghostty/config"

# link starship config
mkdir -p "${HOME}/.config/starship"
ln -sf "${DOTFILES}/config/starship/starship.toml" "${HOME}/.config/starship.toml"