#! /usr/bin/env bash
#MISE description="Reinstall dotfiles"
#MISE depends=["clean", "init"]
echo "Reinstalling dotfiles..."

# Link vimrc
ln -sf "${DOTFILES}/config/vim/.vimrc" "${HOME}/.vimrc"

# copy mise config
# Create config directory if it doesn't exist
mkdir -p "${HOME}/.config/mise"
cp "${DOTFILES}/config/mise.global.toml" "${HOME}/.config/mise/config.toml"

# link ghostty config
# Create config directory if it doesn't exist
mkdir -p "${HOME}/.config/ghostty"
ln -sf "${DOTFILES}/config/ghostty/config.toml" "${HOME}/.config/ghostty/config"