[tools]
act = "latest"
aqua = "latest"
"cargo:bat" = "latest"
"cargo:eza" = "latest"
fzf = "latest"
gemini-cli = "latest"
gh = "latest"
go = "latest"
lazyssh = "latest"
node = "24.13.0"
pipx = "latest"
pnpm = "latest"
python = "latest"
rust = "latest"
usage = "latest"
uv = "latest"
"cargo:zoxide" = "latest"

[settings]
activate_aggressive = true
color_theme = "catppuccin"
experimental = true
