[tools]
gh = "latest"
lazyssh = "latest"
pnpm = "latest"
usage = "latest"
uv = "latest"
zoxide = "latest"
eza = "latest"
fzf = "latest"
"aqua:starship" = "latest"
bat = "latest"

ruby = {version = "latest", os = "macos"}
"gem:try-cli" = {depends = "ruby", version = "latest", os = "macos"}
sheldon = "latest"

[settings]
activate_aggressive = true
color_theme = "catppuccin"
experimental = true

[settings.ruby]
compile = false
